2021-07-10 13:16:18,505 ERROR: Exception on /login [GET] [in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Microblogging - Site\Flask_Web_Application\microblog\app\routes.py", line 72, in login
    return render_template('login.html', form = form, title = 'Sign In')
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Microblogging - Site\Flask_Web_Application\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\HP\Microblogging - Site\Flask_Web_Application\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\HP\Microblogging - Site\Flask_Web_Application\microblog\app\templates\login.html", line 24, in block "content"
    <p>Forgot Password? <a href = "{{url_for('reset_password_request')}}"> Click to Reset it!</a></p>
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2021-07-10 13:19:41,729 ERROR: Exception on /login [GET] [in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\Microblogging - Site\Flask_Web_Application\microblog\app\routes.py", line 72, in login
    return render_template('login.html', form = form, title = 'Sign In')
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\Microblogging - Site\Flask_Web_Application\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\HP\Microblogging - Site\Flask_Web_Application\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\HP\Microblogging - Site\Flask_Web_Application\microblog\app\templates\login.html", line 24, in block "content"
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
